cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    aa:
      email: abc@gmail.com
      first_name: aa
      last_name: bb
      logged_in: false
      password: $2b$12$OfntjNFygpMsfGA3U6NPiOUGeK5GLhAbXEzb6o00zZetphedF4OnG
      password_hint: ??
      roles: null
    jsmith:
      email: bcd@gmail.com
      failed_login_attempts: 0
      first_name: John
      last_name: Smith
      logged_in: false
      password: $2b$12$192UuVmZojQpJ/FQWregze10XehmQ81Y7MfhDpVdXIRtEfW4OyTFa
      roles:
      - admin
      - editor
      - viewer
    rbriggs:
      email: cde@gmail.com
      failed_login_attempts: 0
      first_name: Rebecca
      last_name: Briggs
      logged_in: false
      password: $2b$12$MtieedE7AxyPfp9D83ClOuaW44WUyjxaQ1Ydhhq6r0Z8kIj04RBWa
      roles:
      - viewer
    take:
      email: def@gmail.com
      first_name: kengo
      last_name: takeuchi
      logged_in: false
      password: $2b$12$QOPgHO3Egtb0gzaBh09ggOJ/V9Wywjr8TMa1baLsxj48nDlTwCElu
      password_hint: '?'
      roles: null
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails: []
